In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv('笔记本集合.csv')
df

   price  frequency  RAM  size  disk  SSD  GPU
0  18200        2.6   16  15.4   512  yes  yes
1   4999        1.8    4  13.6   512  yes  yes
2   3699        1.6    4  13.0  1024   no   no
3   9999        1.6    8  14.0   256  yes   no
4   8599        2.2    8  15.6  1024   no  yes
5  23000        2.2   32  15.6  1024  yes  yes
6   4699        2.3    8  13.3   256  yes   no
7   2999        2.6    4  13.0   256  yes   no

In [2]:
# 制定规则，返回质量评分
def get_quality(p):
    res=[]
    if p['size']<14:
        res.append(5)
    elif p['size']>=14:
        res.append(10)
    if p['RAM']<8:
        res.append(4)
    elif p['RAM']>=8:
        res.append(10)
    if p['GPU']=='yes':
        res.append(10)
    elif p['GPU']=='no':
        res.append(3)
#     return res
    return np.mean(res)

# 制定规则，返回经济评分
def get_economy(p):
    res=[]
    if p['price']<=8000:
        res.append(10)
    elif p['price']>8000:
        res.append(6)
    return np.mean(res)

# 制定规则，返回效用值
def get_utility(p):
    return p['quality']*0.4+p['economy']*0.6

df['quality']=df.apply(lambda x:get_quality(x),axis=1)
df['economy']=df.apply(lambda x:get_economy(x),axis=1)
df['utility']=df.apply(lambda x:get_utility(x),axis=1)

In [3]:
df

   price  frequency  RAM  size  disk  SSD  GPU    quality  economy   utility
0  18200        2.6   16  15.4   512  yes  yes  10.000000      6.0  7.600000
1   4999        1.8    4  13.6   512  yes  yes   6.333333     10.0  8.533333
2   3699        1.6    4  13.0  1024   no   no   4.000000     10.0  7.600000
3   9999        1.6    8  14.0   256  yes   no   7.666667      6.0  6.666667
4   8599        2.2    8  15.6  1024   no  yes  10.000000      6.0  7.600000
5  23000        2.2   32  15.6  1024  yes  yes  10.000000      6.0  7.600000
6   4699        2.3    8  13.3   256  yes   no   6.000000     10.0  8.400000
7   2999        2.6    4  13.0   256  yes   no   4.000000     10.0  7.600000